CREATE DATABASE QLKH
USE QLKH

CREATE TABLE GiangVien(
    GV# VARCHAR(10) PRIMARY KEY  ,
    HoTen NVARCHAR(50) NOT NULL,
    DiaChi NVARCHAR(100) NOT NULL,
    NgaySinh DATETIME NOT NULL
)
CREATE TABLE DeTai(
    DT# VARCHAR(10) PRIMARY KEY ,
    TenDT NVARCHAR(100) NOT NULL,
    Cap NVARCHAR(50) NOT NULL,
    KinhPhi INT NOT NULL
)
CREATE TABLE ThamGia(
    GV# VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES [dbo].[GiangVien](GV#) ON UPDATE CASCADE ON DELETE CASCADE,
    DT# VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES [dbo].[DeTai](DT#) ON UPDATE CASCADE ON DELETE CASCADE,
    SoGio INT NOT NULL,
    PRIMARY KEY (GV#,DT#)
   
)
-----------
USE QLKH
CREATE LOGIN PhongNT
    WITH PASSWORD = N'phong123',
    CHECK_EXPIRATION = OFF,
    CHECK_POLICY = OFF
GO
-----------
USE QLKH
CREATE LOGIN PhuongNH
    WITH PASSWORD =N'phuong123',
    CHECK_EXPIRATION =OFF,
    CHECK_POLICY =OFF
GO
----------
CREATE USER PhongNT
    FOR LOGIN PhongNT

-----------------
CREATE USER PhuongNH
    FOR LOGIN PhuongNH
--------
GRANT SELECT
ON  GiangVien  TO PhongNT
------------
GRANT SELECT
ON  ThamGia  TO PhongNT
--------
REVOKE DELETE 
ON ThamGia
FROM PhongNT
--------
CREATE ROLE [Giang_Vien]
GO
 
ALTER ROLE Giang_Vien ADD MEMBER TrinhVT; 
ALTER ROLE Giang_Vien ADD MEMBER KhanhTD; 
GRANT ALTER ANY DATABASE  TO Giang_Vien